//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webmap
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Device()
        {
            this.Ruckus_Log = new HashSet<Ruckus_Log>();
        }
    
        public int DeviceId { get; set; }
        public string DeviceMac { get; set; }
        public string DeviceName { get; set; }
        public Nullable<double> GeoLong { get; set; }
        public Nullable<double> GeoLat { get; set; }
        public List<Ruckus_Log> Logovi { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ruckus_Log> Ruckus_Log { get; set; }
    }
}
