//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webmap
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RuckusLogEntities6 : DbContext
    {
        public RuckusLogEntities6()
            : base("name=RuckusLogEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Device> Device { get; set; }
        public virtual DbSet<EventType> EventType { get; set; }
        public virtual DbSet<Ruckus_Log> Ruckus_Log { get; set; }
        public virtual DbSet<Ssid> Ssid { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
