//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webmap
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ruckus_Log
    {
        public int LogId { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public Nullable<int> EventTypeId { get; set; }
        public Nullable<int> Snr { get; set; }
        public Nullable<int> Rssi { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> DeviceId { get; set; }
        public Nullable<int> SsidId { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual EventType EventType { get; set; }
        public virtual Ssid Ssid { get; set; }
        public virtual User User { get; set; }
    }
}
